name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies for backend project
        run: |
          cd $GITHUB_WORKSPACE/backend
          npm install
      - name: Install dependencies for frontend project
        run: |
          cd $GITHUB_WORKSPACE/web
          npm install
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test:e2e
          working-directory: ./e2e-test
          browser: chrome
