name: Cypress Tests

on: push
env:
  NODE_ENV: ${{ vars.NODE_ENV }}
  PORT: ${{ vars.PORT }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  TOKEN_EXPIRES_IN: ${{ vars.TOKEN_EXPIRES_IN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_SSL: ${{ vars.POSTGRES_SSL }}
  DB_MIGRATE_DROP_TABLES: ${{ vars.DB_MIGRATE_DROP_TABLES }}
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: 
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies for backend project
        run: |
          cd $GITHUB_WORKSPACE/backend
          npm install
      - name: Install dependencies for frontend project
        run: |
          cd $GITHUB_WORKSPACE/web
          npm install
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test:e2e
          working-directory: ./e2e-test
          browser: chrome
          
